### ISSUE TITLE
Tiles clearing in ToB every raid

### ISSUE THREAD

**Issue by Cooper1lols** [WhatATopic/StopMisclickingTiles#1]
If I set certain tiles to be disabled it will work for the current Theatre of blood run I'm currently in, but after going into a new one all disabled walk tiles are removed and have to be manually replaced. Is there a reason for this? or a workaround where I could input certain tile coordinates to always be disabled? such as importing tile markers?

**Comment by WhatATopic** [comment]
Thanks for letting me know about the bug. It will be fixed whenever the updated version is added to the plugin hub.
