### ISSUE TITLE
Being able to click through walls onto disabled tiles

### ISSUE THREAD

**Issue by Cooper1lols** [WhatATopic/StopMisclickingTiles#2]
https://i.imgur.com/nYNYtNh.png Here's a picture of my cursor going through the crafting guild bank and giving me the walk option to the tile behind the wall https://i.imgur.com/CzNFe8u.png and actually moving my character to that tile. https://i.imgur.com/ErqPwVs.png
Other examples of it from different angles. Just seems like at certain places if you click a tile thats hidden through some sort of object or collision it bypasses the the disabled walk option anyway. Idk if this is fixable or not though

**Comment by WhatATopic** [comment]
I can only get that to happen when I click on the disabled tile through a player so it says "Walk here (Player name)." Is that the case for you as well?

**Comment by Cooper1lols** [comment]
Yes that seems to be consistent with how its working. through player and through objects it walks there

**Comment by WhatATopic** [comment]
I fixed the issue with walking to disabled tiles through a player but I could not make it walk to disabled tiles through objects. You can get it to walk to disabled tiles without clicking near another player?

**Comment by Cooper1lols** [comment]
Should be fine then I assumed it was objects causing it but it appears it
was players

**Comment by WhatATopic** [comment]
Alright, thanks again for letting me know about the bug. The runelite devs haven't merged my update for the other bug yet so whenever they merge it, both of the bugs will be fixed.
