### ISSUE TITLE
Disable walk on any invalid object/area

### ISSUE THREAD

**Issue by Florian54321** [WhatATopic/StopMisclickingTiles#3]
Maybe a nice QoL thing to have is when you could disable walking on any movement blocked tiles? Much like the "Invalid Movement" plugin is showing you where you can and cannot go. This would potentially fix your character running in random directions when you missclick.

**Comment by WhatATopic** [comment]
Thanks for the suggestion. Feature has been added as two config options and the plugin will be updated whenever it is merged into the plugin hub. It only works for tiles that cannot be walked on. For example, a tile that has an object on it or a tile that is a wall. I tried to make it work for unreachable tiles that could be walked on but it is not easily done and at this point, its not worth the effort.
