### ISSUE TITLE
How to reset all selected tiles?

### ISSUE THREAD

**Issue by Norkotah** [WhatATopic/StopMisclickingTiles#6]
I tried to make my farm runs misclick-proof by blocking literally every single tile near farming patches I don't actively use. I usually just click directly on the patches and avoid all walk-here actions anyway.

The problem is it turns out I DO have to "walk here" occasionally on places I've blocked and it's actually incredibly annoying not being able to walk anywhere even with a ctrl+click or a right-click walk here. Listen, I know it's my fault for spending 3 hours blocking tiles one night, but I'd just like to start over with a clean slate. Resetting the plugin from the plugin menu and/or deleting the plugin and reinstalling it from the Plugin Hub DOES NOT clear the tiles I've already set though.

Where is the tile information stored? I just want to clear all the tiles I've set at once. If they can only be cleared one at a time I'm probably going to have to discontinue use of the plugin.

**Comment by WhatATopic** [comment]
The tile information is stored in the Runelite properties file. 
I believe you would navigate to C:\Users\ (name) \\.runelite\profiles2
You would edit the properties file with notepad or whatever and search for "smt.region"
Then you would delete the line and search for it again until there are none left. I'm sorry there isn't an easier way, I didn't think about people marking a ton of tiles.

**Comment by Norkotah** [comment]
Thanks, it's not a problem having to go through the file. Just knowing where to find the file is a huge help. For anyone who stumbles into this with the same issue, here is how to easily delete all "smt.region" lines at once.

1. Open the properties file in Notepad++
2. Ctrl+F and go to the "Mark" tab at the end
3. Type in **smt.region** in the "Find What" field
4. Make sure "Bookmark Line" is checked below
5. Click "Mark All" on the right
6. Close the Find screen on click on "Search" on the top menu
7. Find the "Bookmark" tab and open the context menu
8. Click on "Remove Bookmarked Lines"
